#! /usr/bin/bash
if [[ $# -lt 1 ]]; then
    echo "Argument missing for bucket name"
    exit 1
fi

if [[ !($1 =~ ^[a-z0-9]+[a-z0-9-]*$) ]]; then
    echo "Invalid bucket name"
    exit 1
fi

aws s3api delete-bucket \
    --bucket $1 \
    --output json
exit 0 